import Head from "next/head";
import Header from "./components/header";
import { useEffect, useState } from "react";
import Post from "./components/post";
import Posting from "./components/ posting";

type Obj = {
  id: null | undefined;
  title: String;
  content: String;
};

export default function Home() {
  const [values, setValues] = useState({ title: "", content: "" });
  const [itemList, setItemList] = useState<Obj[]>([]);

  const getList = () => {
    fetch("../api/hello", {
      method: "GET",
    })
      .then((res) => res.json())
      .then((data) => {
        console.log(data);
        setItemList(data);
        console.log(itemList);
      });
  };

  useEffect(() => {
    getList();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={``}>
        <Post values={values} setValues={setValues} getList={getList} />

        <Posting itemList={itemList} getList={getList} />
      </main>
    </>
  );
}
