import Head from "next/head";
import Header from "./components/header";
import { useState } from "react";

export default function Home() {
  const [values, setValues] = useState({ title: "", content: "" });

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const val = e.target.value;
    const name = e.target.name;
    setValues({ ...values, [name]: val });
  };

  const handlePost = () => {
    fetch("../api/hello").then(() => console.log("追加"));
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={``}>
        <div>
          <input
            type="text"
            onChange={handleChange}
            value={values.title}
            name="title"
          />
          <input
            type="text"
            onChange={handleChange}
            value={values.content}
            name="content"
          />
          <button onClick={handlePost}>追加</button>
        </div>
      </main>
    </>
  );
}
