import Head from "next/head";
import Header from "./components/header";
import { useEffect, useState } from "react";

export default function Home() {
  const [values, setValues] = useState({ title: "", content: "" });

  useEffect(() => {
    fetch("../api/hello", {
      method: "GET",
    })
      .then((res) => res.json())
      .then((data) => console.log(data));
  }, []);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const val = e.target.value;
    const name = e.target.name;
    setValues({ ...values, [name]: val });
  };

  const handlePost = async () => {
    const data = {
      title: values.title,
      content: values.content,
    };
    await fetch("../api/hello", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(data),
    })
      .then((res) => res.json())
      .then((data) => {
        alert("投稿しました");
        console.log(data);
      });
    setValues({ ...values, title: "" });
    setValues({ ...values, content: "" });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={``}>
        <div>
          <input
            type="text"
            onChange={handleChange}
            value={values.title}
            name="title"
          />
          <input
            type="text"
            onChange={handleChange}
            value={values.content}
            name="content"
          />
          <button onClick={handlePost}>追加</button>
        </div>
      </main>
    </>
  );
}
